# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: build and test
on: [push]

jobs:
  build:
    name: ${{ matrix.toolchain.name }}
    strategy:
      matrix:
        toolchain:
          - {runs_on: ubuntu-latest, name: "Clang 9", CC: clang-9, CXX: clang++-9, CFLAGS: "", WARNINGS: "-Werror"}
          - {runs_on: ubuntu-latest, name: "Clang 9 ASAN+UBSAN", CC: clang-9, CXX: clang++-9, CFLAGS: "-fsanitize=address,undefined -fno-sanitize-recover=address,undefined", WARNINGS: "-Werror"}
          - {runs_on: ubuntu-latest, name: "GCC 8", CC: gcc-8, CXX: g++-8, CFLAGS: "", WARNINGS: "-Werror"}
          - {runs_on: ubuntu-latest, name: "GCC 8 ASAN+UBSAN", CC: gcc-8, CXX: g++-8, CFLAGS: "-fsanitize=address,undefined -fno-sanitize-recover=address,undefined", WARNINGS: "-Werror"}
          - {runs_on: windows-latest, name: "MSVC", CFLAGS: "", WARNINGS: ""}
    runs-on: ${{ matrix.toolchain.runs_on }}
    env:
      CMAKE_C_COMPILER: ${{ matrix.toolchain.CC }}
      CMAKE_C_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      CMAKE_CXX_COMPILER: ${{ matrix.toolchain.CXX }}
      CMAKE_CXX_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      CMAKE_EXE_LINKER_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      CMAKE_SHARED_LINKER_FLAGS: ${{ matrix.toolchain.CFLAGS }}
      QUICK_LINT_JS_CXX_COMPILER_OPTIONS: ${{ matrix.toolchain.WARNINGS }}
    steps:
      - name: check out
        uses: actions/checkout@v1
      - name: configure
        run: |
          env | grep '^CMAKE\|^QUICK_LINT_JS' | sort
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=YES ${CMAKE_C_COMPILER+-DCMAKE_C_COMPILER="${CMAKE_C_COMPILER}"} ${CMAKE_CXX_COMPILER+-DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}"} -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS}" -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}" -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS}" -DCMAKE_SHARED_LINKER_FLAGS="${CMAKE_SHARED_LINKER_FLAGS}" -DQUICK_LINT_JS_CXX_COMPILER_OPTIONS="${QUICK_LINT_JS_CXX_COMPILER_OPTIONS}" -S . -B .
        shell: bash
      - name: build
        run: cmake --build . --config Debug
      - name: test
        run: ctest --build-config Debug --verbose
