# Copyright (C) 2020  Matthew Glazar
# See end of file for extended copyright information.

name: Debian package
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  # TODO(strager): Also build ARM (32-bit) .deb-s.
  build-deb:
    name: build .deb (${{ matrix.os.platform }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - {runs_on: ubuntu-latest, docker_container: "ghcr.io/quick-lint/quick-lint-js-github-builder:v1", platform: x86_64}
          - {runs_on: stracle-debian-aarch64, docker_container: "ghcr.io/quick-lint/quick-lint-js-github-builder-aarch64:v2", platform: aarch64}
    runs-on: ${{ matrix.os.runs_on }}
    container: ${{ matrix.os.docker_container }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: ./dist/debian/build.sh

      - name: upload build to workflow
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: quick-lint-js-deb-${{ matrix.os.platform }}-${{ github.sha }}
          path: |
            dist/debian/quick-lint-js-dbgsym_*
            dist/debian/quick-lint-js-vim_*
            dist/debian/quick-lint-js_*
      - name: upload build to long-term storage
        if: ${{ github.event_name == 'push' && github.repository_owner == 'quick-lint' != null }}
        uses: quick-lint/sftp-upload@master
        with:
          host: ${{ secrets.artifacts_host }}
          local-file-globs: |
            dist/debian/quick-lint-js-dbgsym_*
            dist/debian/quick-lint-js-vim_*
            dist/debian/quick-lint-js_*
          private-key: ${{ secrets.artifacts_key }}
          remote-directory: ${{ secrets.artifacts_root }}/builds/${{ github.sha }}/debian/${{ matrix.os.platform }}
          user: ${{ secrets.artifacts_user }}

  test-deb:
    name: test on ${{ matrix.os.name }} (${{ matrix.os.platform }})
    needs: build-deb
    strategy:
      fail-fast: false
      matrix:
        os:
          - {runs_on: ubuntu-latest, docker_container: "debian:buster", name: "Debian 10 Buster", platform: x86_64}
          - {runs_on: ubuntu-latest, docker_container: "debian:stretch", name: "Debian 9 Stretch", platform: x86_64}
          - {runs_on: ubuntu-latest, docker_container: "pureos/pureos:amber-latest", name: "PureOS Amber", platform: x86_64}
          - {runs_on: ubuntu-latest, docker_container: "ubuntu:16.04", name: "Ubuntu 16.04 LTS Xenial", platform: x86_64}
          - {runs_on: ubuntu-latest, docker_container: "ubuntu:18.04", name: "Ubuntu 18.04 LTS Bionic", platform: x86_64}
          - {runs_on: ubuntu-latest, docker_container: "ubuntu:20.04", name: "Ubuntu 20.04 LTS Focal", platform: x86_64}
    runs-on: ${{ matrix.os.runs_on }}
    container: ${{ matrix.os.docker_container }}

    steps:
      - name: OS information
        run: |
          exec 2>&1
          set -x

          cat /etc/lsb-release || :
          cat /etc/os-release || :
          cat /etc/system-release || :
          uname -a || :

      - name: update apt
        run: apt-get update

      - uses: actions/download-artifact@v2
        with:
          name: quick-lint-js-deb-${{ matrix.os.platform }}-${{ github.sha }}

      - name: install quick-lint-js
        run: dpkg -i quick-lint-js_*.deb
      - name: test quick-lint-js
        run: quick-lint-js --version

      - name: install quick-lint-js-vim dependencies
        run: DEBIAN_FRONTEND=noninteractive apt-get install -y vim vim-addon-manager
      - name: install quick-lint-js-vim
        run: dpkg -i quick-lint-js-vim_*.deb

# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This file is part of quick-lint-js.
#
# quick-lint-js is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# quick-lint-js is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with quick-lint-js.  If not, see <https://www.gnu.org/licenses/>.
