# quick-lint-js finds bugs in JavaScript programs.
# Copyright (C) 2020  Matthew Glazar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: test Vim plugin
on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: ${{ matrix.vim.name }}
    strategy:
      fail-fast: false
      matrix:
        vim:
          - {name: "Neovim", packages: "neovim", version_command: "nvim --version", test_command: "./plugin/vim/test-nvim.sh"}
          - {name: "Vim", packages: "vim", version_command: "vim --version", test_command: "./plugin/vim/test-vim.sh"}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2
      - name: checkout
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: install ${{ matrix.vim.name }}
        run: sudo apt-get install ${{ matrix.vim.packages }}
      - name: version
        run: ${{ matrix.vim.version_command }}

      - name: test
        run: ${{ matrix.vim.test_command }}
